// =============================================================
//  knn_tb.v  -  Testbench for knn_top.v
//  Feeds test samples one feature at a time, collects predictions
//  and compares against ground-truth labels from Python export.
//  UPDATED: Parameters synced to Python export (90 features, K=7,
//           958 train, distance-weighted vote in DUT)
// =============================================================

`timescale 1ns / 1ps

module knn_tb;

    // ── Parameters (must match knn_top exactly) ───────────────
    parameter NUM_FEATURES  = 90;   // 85 original + 5 engineered  ← UPDATED
    parameter NUM_TRAIN     = 958;  //                              ← UPDATED
    parameter NUM_TEST      = 240;
    parameter K             = 7;    //                              ← UPDATED
    parameter FEATURE_WIDTH = 16;
    parameter DIST_WIDTH    = 24;   //                              ← UPDATED
    parameter NUM_CLASSES   = 4;
    parameter LABEL_WIDTH   = 2;

    // ── DUT signals ───────────────────────────────────────────
    reg  clk, rst_n;
    reg  query_valid;
    reg  [FEATURE_WIDTH-1:0]         query_data;
    reg  [$clog2(NUM_FEATURES)-1:0]  query_idx;
    wire [LABEL_WIDTH-1:0]           pred_label;
    wire                             pred_valid;

    // ── Test data memory ──────────────────────────────────────
    reg [FEATURE_WIDTH-1:0] test_data  [0:NUM_TEST*NUM_FEATURES-1];
    reg [LABEL_WIDTH-1:0]   test_label [0:NUM_TEST-1];

    // ── Metrics ───────────────────────────────────────────────
    integer correct, total;
    integer i, f;
    integer cm [0:NUM_CLASSES-1][0:NUM_CLASSES-1];
    integer ci, cj;

    // Per-class TP/FP/FN for precision/recall
    integer tp [0:NUM_CLASSES-1];
    integer fp [0:NUM_CLASSES-1];
    integer fn [0:NUM_CLASSES-1];
    real    prec, rec, f1;

    // ── Clock (100 MHz) ───────────────────────────────────────
    always #5 clk = ~clk;

    // ── DUT instantiation ─────────────────────────────────────
    knn_top #(
        .NUM_FEATURES (NUM_FEATURES),
        .NUM_TRAIN    (NUM_TRAIN),
        .K            (K),
        .FEATURE_WIDTH(FEATURE_WIDTH),
        .DIST_WIDTH   (DIST_WIDTH),
        .NUM_CLASSES  (NUM_CLASSES),
        .LABEL_WIDTH  (LABEL_WIDTH)
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),
        .query_valid(query_valid),
        .query_data (query_data),
        .query_idx  (query_idx),
        .pred_label (pred_label),
        .pred_valid (pred_valid)
    );

    // ── Test procedure ────────────────────────────────────────
    initial begin
        $dumpfile("knn_tb.vcd");
        $dumpvars(0, knn_tb);

        // Load test data generated by Python
        $readmemh("knn_test_data.mem",   test_data);
        $readmemh("knn_test_labels.mem", test_label);

        // Initialise confusion matrix and per-class counters
        for (ci = 0; ci < NUM_CLASSES; ci = ci + 1) begin
            tp[ci] = 0; fp[ci] = 0; fn[ci] = 0;
            for (cj = 0; cj < NUM_CLASSES; cj = cj + 1)
                cm[ci][cj] = 0;
        end

        // Reset
        clk         = 0;
        rst_n       = 0;
        query_valid = 0;
        query_data  = 0;
        query_idx   = 0;
        correct     = 0;
        total       = 0;

        @(posedge clk); #1;
        @(posedge clk); #1;
        rst_n = 1;
        @(posedge clk); #1;

        // ── Iterate over test samples ──────────────────────────
        for (i = 0; i < NUM_TEST; i = i + 1) begin
            for (f = 0; f < NUM_FEATURES; f = f + 1) begin
                @(posedge clk); #1;
                query_valid = 1;
                query_data  = test_data[i * NUM_FEATURES + f];
                query_idx   = f;
            end
            @(posedge clk); #1;
            query_valid = 0;

            wait(pred_valid);
            @(posedge clk); #1;

            // Update confusion matrix
            cm[test_label[i]][pred_label] = cm[test_label[i]][pred_label] + 1;

            // Update per-class TP/FP/FN
            if (pred_label == test_label[i]) begin
                tp[test_label[i]] = tp[test_label[i]] + 1;
                correct = correct + 1;
            end else begin
                fn[test_label[i]] = fn[test_label[i]] + 1;
                fp[pred_label]    = fp[pred_label]    + 1;
            end
            total = total + 1;

            if ((i % 50) == 0)
                $display("Sample %0d / %0d  true=%0d  pred=%0d",
                         i, NUM_TEST, test_label[i], pred_label);
        end

        // ── Results ───────────────────────────────────────────
        $display("\n==================================================");
        $display("KNN FPGA Simulation Results");
        $display("==================================================");
        $display("K = %0d   Metric = Manhattan   Features = %0d",
                 K, NUM_FEATURES);
        $display("Voting  = distance-weighted (MAX_D - d approx)");
        $display("Correct  : %0d / %0d", correct, total);
        $display("Accuracy : %0.2f%%", (100.0 * correct) / total);

        $display("\nConfusion Matrix (rows=True, cols=Predicted):");
        $display("             Healthy  Fault1  Fault2  Fault3");
        for (ci = 0; ci < NUM_CLASSES; ci = ci + 1) begin
            case (ci)
                0: $write("Healthy   ");
                1: $write("Fault1    ");
                2: $write("Fault2    ");
                3: $write("Fault3    ");
            endcase
            for (cj = 0; cj < NUM_CLASSES; cj = cj + 1)
                $write("  %6d", cm[ci][cj]);
            $display("");
        end

        $display("\nPer-Class Precision / Recall / F1:");
        $display("  %-10s  Prec    Rec     F1", "Class");
        for (ci = 0; ci < NUM_CLASSES; ci = ci + 1) begin
            if ((tp[ci] + fp[ci]) > 0)
                prec = (100.0 * tp[ci]) / (tp[ci] + fp[ci]);
            else
                prec = 0.0;
            if ((tp[ci] + fn[ci]) > 0)
                rec  = (100.0 * tp[ci]) / (tp[ci] + fn[ci]);
            else
                rec  = 0.0;
            if ((prec + rec) > 0)
                f1 = (2.0 * prec * rec) / (prec + rec);
            else
                f1 = 0.0;
            case (ci)
                0: $write("  Healthy   ");
                1: $write("  Fault1    ");
                2: $write("  Fault2    ");
                3: $write("  Fault3    ");
            endcase
            $display("  %5.2f%%  %5.2f%%  %5.2f%%", prec, rec, f1);
        end

        $display("==================================================\n");
        $finish;
    end

    // ── Timeout watchdog ─────────────────────────────────────
    // Worst-case cycles: NUM_TEST × (NUM_FEATURES + NUM_TRAIN×NUM_FEATURES
    //                                + NUM_TRAIN + 10 margin)
    // ≈ 240 × (90 + 958×90 + 958 + 10) ≈ 240 × 87308 ≈ 20.9 M cycles
    // At 10 ns/cycle → ~209 ms → set timeout to 300 ms = 300_000_000 ns
    initial begin
        #300_000_000;
        $display("TIMEOUT: simulation exceeded 300 ms limit");
        $finish;
    end

endmodule